server:
  port: 0

spring:
  application:
    name: jogayjoga-court
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jogayjoga}
    username: ${DATABASE_USERNAME:jogayjoga}
    password: ${DATABASE_PASSWORD:jogayjoga}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: court
  jpa:
    properties:
      hibernate:
        default_schema: court
  redis:
    host: my-redis
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: court
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false

springdoc:
  api-docs:
    path: /court/api-docs
  swagger-ui:
    path: /court/swagger-ui.html

management:
  endpoints:
    web:
      base-path: /courts/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}